doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    mapping_types:
        enum: string

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '15'

    profiling_collect_backtrace: '%kernel.debug%'
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    report_fields_where_declared: true
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    dql:
      string_functions:
        group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
    mappings:
      Space:
        is_bundle: false
        dir: '%kernel.project_dir%/src/Space/Infrastructure/DB/MySQL/Entity'
        prefix: 'Fynkus\Space\Infrastructure\DB\MySQL\Entity'
        alias: Space
      Reservation:
          is_bundle: false
          type: attribute
          dir: '%kernel.project_dir%/src/Reservation/Infrastructure/DB/MySQL/Entity'
          prefix: 'Fynkus\Reservation\Infrastructure\DB\MySQL\Entity'
          alias: Reservation




when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system